#!/usr/bin/env sh

WIDTH=${WIDTH:-200}
HEIGHT=${HEIGHT:-200}
DATEFMT=${DATEFMT:-"+%a %d.%m.%Y %H:%M:%S"}
SHORTFMT=${SHORTFMT:-"+%H:%M:%S"}

OPTIND=1
while getopts ":f:W:H:" opt; do
    case $opt in
        f) DATEFMT="$OPTARG" ;;
        W) WIDTH="$OPTARG" ;;
        H) HEIGHT="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case "$BLOCK_BUTTON" in
    1|2|3)
        # Get the current mouse position
        eval $(xdotool getmouselocation --shell)

        # Calculate the position of the upper left corner of the popup
        posX=$(($X - $WIDTH / 2))
        posY=$(($Y - $HEIGHT))

        # Ensure the popup stays within the screen boundaries
        SCREEN_WIDTH=$(xdotool getdisplaygeometry | awk '{print $1}')
        SCREEN_HEIGHT=$(xdotool getdisplaygeometry | awk '{print $2}')

        if [ $posX -lt 0 ]; then posX=0; fi
        if [ $posY -lt 0 ]; then posY=0; fi
        if [ $(($posX + $WIDTH)) -gt $SCREEN_WIDTH ]; then posX=$(($SCREEN_WIDTH - $WIDTH)); fi
        if [ $(($posY + $HEIGHT)) -gt $SCREEN_HEIGHT ]; then posY=$(($SCREEN_HEIGHT - $HEIGHT)); fi

        # Run yad with the calculated position
        yad --calendar \
            --width=$WIDTH --height=$HEIGHT \
            --undecorated --fixed \
            --close-on-unfocus --no-buttons \
            --posx=$posX --posy=$posY \
            > /dev/null
        ;;
esac

echo "$LABEL$(date "$DATEFMT")"

